### ISSUE TITLE
【可视化埋点】页面区块有时候能响应，有时点击无法响应

### ISSUE THREAD

**Issue by TimXiongTing** [Datafruit/sugo-android-sdk#2]
页面区块有时候能响应，有时点击无法响应
![1612091509](https://cloud.githubusercontent.com/assets/24470629/21040728/97670124-be21-11e6-873e-2ebbc038e02a.png)

**Comment by xianjingfeng** [comment]
原因是这里是一个iframe，页面还没加载完成，正常现象
