### ISSUE TITLE
启动activity变慢

### ISSUE THREAD

**Issue by mohuaqing** [Datafruit/sugo-android-sdk#223]
因为遍历的当前window的所有view和使用了反射，如果页面复杂，会造成页面切换慢，
还有EditState 类中的集合 mCurrentEdits是否没有释放？

**Comment by Null-Ouwenjie** [comment]
@mohuaqing 谢谢建议

1 目前定位 View 是通过记录 View 的路径，然后遍历 rootView 来实现的。
2 使用了反射，具体是指哪一个方法里使用？使用不频繁的话是不影响性能的。
3 mCurrentEdits 保存的 EditBinding 类，其引用的变量会被释放或者 WeakReference 。当然之后再释放 EditBinding 类就更好了。
