### ISSUE TITLE
【可视化埋点】点击了human，显示robot

### ISSUE THREAD

**Issue by TimXiongTing** [Datafruit/sugo-android-sdk#3]
点击了human，显示robot
![1612091540](https://cloud.githubusercontent.com/assets/24470629/21041422/dd8cd4fe-be25-11e6-877d-a699faf80bf1.png)

**Comment by xianjingfeng** [comment]
fixed    https://github.com/Datafruit/sugo-android-sdk/commit/1b32d2ad557b438004202ddac5e656c73d9caed5
